code/project_services/page/views.py
from flask import Blueprint, render_template
from flask import current_app as app
from server_app_extensions import cache
import sys

page_blueprint = Blueprint('page', __name__, template_folder='templates')

@page_blueprint.route('/')
@cache.cached(timeout=1000)
def home():

    msg = sys.version
    return render_template('page/home.html', msg=msg)

@page_blueprint.route('/terms')
def terms():
    return render_template('page/terms.html')


@page_blueprint.route('/privacy')
def privacy():
    return render_template('page/privacy.html')

code/project_services/user/views.py
from flask import (
    Blueprint,
    redirect,
    request,
    flash,
    url_for,
    render_template)
from flask_login import (
    login_required,
    login_user,
    current_user,
    logout_user)

from app_library.lib_safe_next_url import safe_next_url
from project_services.user.decorators import anonymous_required
from project_services.user.models import User
from project_services.user.forms import (
    LoginForm,
    BeginPasswordResetForm,
    PasswordResetForm,
    SignupForm,
    WelcomeForm,
    UpdateCredentials)

user_blueprint = Blueprint('user', __name__, template_folder='templates')


@user_blueprint.route('/login', methods=['GET', 'POST'])
@anonymous_required()
def login():
    form = LoginForm(next=request.args.get('next'))

    if form.validate_on_submit():
        u = User.find_by_identity(request.form.get('identity'))

        if u and u.authenticated(password=request.form.get('password')):
            # As you can see remember me is always enabled, this was a design
            # decision I made because more often than not users want this
            # enabled. This allows for a less complicated login form.
            #
            # If however you want them to be able to select whether or not they
            # should remain logged in then perform the following 3 steps:
            # 1) Replace 'True' below with: request.form.get('remember', False)
            # 2) Uncomment the 'remember' field in user/forms.py#LoginForm
            # 3) Add a checkbox to the login form with the id/name 'remember'
            if login_user(u, remember=True) and u.is_active():
                u.update_activity_tracking(request.remote_addr)

                # Handle optionally redirecting to the next URL safely.
                next_url = request.form.get('next')
                if next_url:
                    return redirect(safe_next_url(next_url))

                return redirect(url_for('user.settings'))
            else:
                flash('This account has been disabled.', 'error')
        else:
            flash('Identity or password is incorrect.', 'error')

    return render_template('user/login.html', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'success')
    return redirect(url_for('user.login'))


@user_blueprint.route('/account/begin_password_reset', methods=['GET', 'POST'])
@anonymous_required()
def begin_password_reset():
    form = BeginPasswordResetForm()

    if form.validate_on_submit():
        u = User.initialize_password_reset(request.form.get('identity'))

        flash('An email has been sent to {0}.'.format(u.email), 'success')
        return redirect(url_for('user.login'))

    return render_template('user/begin_password_reset.html', form=form)


@user_blueprint.route('/account/password_reset', methods=['GET', 'POST'])
@anonymous_required()
def password_reset():
    form = PasswordResetForm(reset_token=request.args.get('reset_token'))

    if form.validate_on_submit():
        u = User.deserialize_token(request.form.get('reset_token'))

        if u is None:
            flash('Your reset token has expired or was tampered with.',
                  'error')
            return redirect(url_for('user.begin_password_reset'))

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        if login_user(u):
            flash('Your password has been reset.', 'success')
            return redirect(url_for('user.settings'))

    return render_template('user/password_reset.html', form=form)


@user_blueprint.route('/signup', methods=['GET', 'POST'])
@anonymous_required()
def signup():
    form = SignupForm()

    if form.validate_on_submit():
        u = User()

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        if login_user(u):
            flash('Awesome, thanks for signing up!', 'success')
            return redirect(url_for('user.welcome'))

    return render_template('user/signup.html', form=form)


@user_blueprint.route('/welcome', methods=['GET', 'POST'])
@login_required
def welcome():
    if current_user.username:
        flash('You already picked a username.', 'warning')
        return redirect(url_for('user.settings'))

    form = WelcomeForm()

    if form.validate_on_submit():
        current_user.username = request.form.get('username')
        current_user.save()

        flash('Sign up is complete, enjoy our services.', 'success')
        return redirect(url_for('user.settings'))

    return render_template('user/welcome.html', form=form)


@user_blueprint.route('/settings')
@login_required
def settings():
    return render_template('user/settings.html')


@user_blueprint.route('/settings/update_credentials', methods=['GET', 'POST'])
@login_required
def update_credentials():
    form = UpdateCredentials(current_user, uid=current_user.id)

    if form.validate_on_submit():
        new_password = request.form.get('password', '')
        current_user.email = request.form.get('email')

        if new_password:
            current_user.password = User.encrypt_password(new_password)

        current_user.save()

        flash('Your sign in settings have been updated.', 'success')
        return redirect(url_for('user.settings'))

    return render_template('user/update_credentials.html', form=form)

code/templates/layouts/app.html
{% extends 'layouts/base.html' %}

{% block header %}
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse" data-target="#navbar"
                aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="{{ url_for('page.home') }}">
          <img src="{{ url_for('static', filename='images/bf.jpg') }}"
               class="img-responsive"
               width="229" height="50" title="bf" alt="bf"/>
        </a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.role == 'admin' %}
          <li>
            {% include 'admin/_menu.html' %}
          </li>
        {% endif %}
          {% if current_user.is_authenticated %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle"
                 data-toggle="dropdown"
                 role="button" aria-haspopup="true"
                 aria-expanded="false">Account
                <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{{ url_for('user.settings') }}">Settings</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Session</li>
                  <li><a href="{{ url_for('user.logout') }}">Log out</a></li>
                </ul>
            </li>
          {% else %}
            <li><a href="{{ url_for('user.login') }}">Log in</a></li>
            <li><a href="{{ url_for('user.signup') }}">Sign up</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
{% endblock %}

{% block footer %}

 {% if current_user.is_authenticated %}
 Hi {{ current_user.name }}!
 {% endif %}


  <li><a href="{{ url_for('contact.index') }}">Contact</a></li>
  <li><a href="{{ url_for('page.privacy') }}">Privacy Policy</a></li>
  <li><a href="{{ url_for('page.terms') }}">Terms of Service</a></li>
{% endblock %}

code/templates/layouts/base.html
{% import 'macros/flash.html' as flash with context %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description"content="{% block meta_description %}{% endblock %}">
       <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{% block title %}{% endblock %}</title>

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/vendor/bootstrap.min.css') }}">
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/main.css') }}">
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/vendor/font-awesome.min.css') }}">
    <script src="https://code.jquery.com/jquery-1.12.2.min.js"
            integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="
            crossorigin="anonymous"></script>
  </head>
  <body>
    {% block header %}{% endblock %}
    
    <main class="container">
      {{ flash.render() }}

      <div class="md-margin-top">{% block heading %}{% endblock %}</div>
      {% block body %}{% endblock %}
    </main>

    <footer class="footer text-center">
      <div class="container">
        <ul class="list-inline">
          <li class="text-muted">BF &copy; 2020</li>
          {% block footer %}{% endblock %}
        </ul>
      </div>
    </footer>

    <script
      src="{{ url_for('static', filename='scripts/vendor/bootstrap.min.js') }}">
    </script>
    <script
      src="{{ url_for('static', filename='scripts/vendor/moment.min.js') }}">
    </script>
    <script
      src="{{ url_for('static', filename='scripts/main.js') }}">
    </script>
  </body>
</html>

code/templates/layouts/login.html
{% extends 'layouts/base.html' %}

{% block header %}
  <a href="{{ url_for('page.home') }}">
    <img src="{{ url_for('static', filename='images/bf-large.jpg') }}"
         class="img-responsive center-block md-margin-bottom"
         width="178" height="176" title="BF" alt="BF"/>
  </a>
{% endblock %}

{% block footer %}
  <li><a href="">Sign up today</a></li>
{% endblock %}