code/project_services/user/views.py
from flask import (
    Blueprint,
    redirect,
    request,
    flash,
    url_for,
    render_template)
from flask_login import (
    login_required,
    login_user,
    current_user,
    logout_user)

from app_library.lib_safe_next_url import safe_next_url
from project_services.user.decorators import anonymous_required
from project_services.user.models import User
from project_services.user.forms import (
    LoginForm,
    BeginPasswordResetForm,
    PasswordResetForm,
    SignupForm,
    WelcomeForm,
    UpdateCredentials)

user_blueprint = Blueprint('user', __name__, template_folder='templates')


@user_blueprint.route('/login', methods=['GET', 'POST'])
@anonymous_required()
def login():
    form = LoginForm(next=request.args.get('next'))

    if form.validate_on_submit():
        u = User.find_by_identity(request.form.get('identity'))

        if u and u.authenticated(password=request.form.get('password')):
            # As you can see remember me is always enabled, this was a design
            # decision I made because more often than not users want this
            # enabled. This allows for a less complicated login form.
            #
            # If however you want them to be able to select whether or not they
            # should remain logged in then perform the following 3 steps:
            # 1) Replace 'True' below with: request.form.get('remember', False)
            # 2) Uncomment the 'remember' field in user/forms.py#LoginForm
            # 3) Add a checkbox to the login form with the id/name 'remember'
            if login_user(u, remember=True) and u.is_active():
                u.update_activity_tracking(request.remote_addr)

                # Handle optionally redirecting to the next URL safely.
                next_url = request.form.get('next')
                if next_url:
                    return redirect(safe_next_url(next_url))

                return redirect(url_for('user.settings'))
            else:
                flash('This account has been disabled.', 'error')
        else:
            flash('Identity or password is incorrect.', 'error')

    return render_template('user/login.html', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'success')
    return redirect(url_for('user.login'))


@user_blueprint.route('/account/begin_password_reset', methods=['GET', 'POST'])
@anonymous_required()
def begin_password_reset():
    form = BeginPasswordResetForm()

    if form.validate_on_submit():
        u = User.initialize_password_reset(request.form.get('identity'))

        flash('An email has been sent to {0}.'.format(u.email), 'success')
        return redirect(url_for('user.login'))

    return render_template('user/begin_password_reset.html', form=form)


@user_blueprint.route('/account/password_reset', methods=['GET', 'POST'])
@anonymous_required()
def password_reset():
    form = PasswordResetForm(reset_token=request.args.get('reset_token'))

    if form.validate_on_submit():
        u = User.deserialize_token(request.form.get('reset_token'))

        if u is None:
            flash('Your reset token has expired or was tampered with.',
                  'error')
            return redirect(url_for('user.begin_password_reset'))

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        if login_user(u):
            flash('Your password has been reset.', 'success')
            return redirect(url_for('user.settings'))

    return render_template('user/password_reset.html', form=form)


@user_blueprint.route('/signup', methods=['GET', 'POST'])
@anonymous_required()
def signup():
    form = SignupForm()

    if form.validate_on_submit():
        u = User()

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        if login_user(u):
            flash('Awesome, thanks for signing up!', 'success')
            return redirect(url_for('user.welcome'))

    return render_template('user/signup.html', form=form)


@user_blueprint.route('/welcome', methods=['GET', 'POST'])
@login_required
def welcome():
    if current_user.username:
        flash('You already picked a username.', 'warning')
        return redirect(url_for('user.settings'))

    form = WelcomeForm()

    if form.validate_on_submit():
        current_user.username = request.form.get('username')
        current_user.save()

        flash('Sign up is complete, enjoy our services.', 'success')
        return redirect(url_for('user.settings'))

    return render_template('user/welcome.html', form=form)


@user_blueprint.route('/settings')
@login_required
def settings():
    return render_template('user/settings.html')


@user_blueprint.route('/settings/update_credentials', methods=['GET', 'POST'])
@login_required
def update_credentials():
    form = UpdateCredentials(current_user, uid=current_user.id)

    if form.validate_on_submit():
        new_password = request.form.get('password', '')
        current_user.email = request.form.get('email')

        if new_password:
            current_user.password = User.encrypt_password(new_password)

        current_user.save()

        flash('Your sign in settings have been updated.', 'success')
        return redirect(url_for('user.settings'))

    return render_template('user/update_credentials.html', form=form)

code/project_services/user/templates/user/begin_password_reset.html
{% extends 'layouts/login.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Reset your password{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-4 col-md-offset-4 well">
      {% call f.form_tag('user.begin_password_reset') %}
        <legend>Reset your password</legend>
        <p class="small help-block sm-margin-bottom">
          We'll send you an email to reset your password.
        </p>

        {% call f.form_group(form.identity, css_class='sm-margin-bottom',
                             autofocus='autofocus') %}
        {% endcall %}

        <div class="row">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              Continue
            </button>
          </div>
          <div class="col-md-6">
            <div class="visible-xs visible-sm sm-margin-top"></div>
            <a href="{{ url_for('user.login') }}"
                class="btn btn-default btn-block">
              Back to login
            </a>
          </div>
        </div>
      {% endcall %}
    </div>
  </div>
{% endblock %}

code/project_services/user/templates/user/login.html
{% extends 'layouts/login.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Sign in to access your account{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-4 col-md-offset-4 well">
      {% call f.form_tag('user.login') %}
        <legend>Sign in to continue</legend>

        {% call f.form_group(form.identity, css_class='sm-margin-bottom',
                             autofocus='autofocus') %}
        {% endcall %}

        {% call f.form_group(form.password, css_class='sm-margin-bottom') %}
        {% endcall %}

        <div class="row">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              Sign in
            </button>
          </div>
          <div class="col-md-6">
            <div class="visible-xs visible-sm sm-margin-top"></div>
            <a href="{{ url_for('user.signup') }}"
               class="btn btn-default btn-block">
              Register
            </a>
          </div>
        </div>
      {% endcall %}

      <div class="text-center md-margin-top">
        <a href="{{ url_for('user.begin_password_reset') }}" class="text-muted">
          Forgot your password?
        </a>
      </div>
    </div>
  </div>
{% endblock %}

code/project_services/user/templates/user/password_reset.html
{% extends 'layouts/login.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Enter a new password{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-4 col-md-offset-4 well">
      {% call f.form_tag('user.password_reset') %}
        <legend>Enter a new password</legend>

        {% call f.form_group(form.password, css_class='sm-margin-bottom') %}
        {% endcall %}

        <div class="row">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              Continue
            </button>
          </div>
          <div class="col-md-6">
            <div class="visible-xs visible-sm sm-margin-top"></div>
            <a href="{{ url_for('user.login') }}"
               class="btn btn-default btn-block">
              Back to login
            </a>
          </div>
        </div>
      {% endcall %}
    </div>
  </div>
{% endblock %}

code/project_services/user/templates/user/settings.html
{% extends 'layouts/app.html' %}

{% block title %}Account settings{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-5">
      <h2>Settings</h2>
      <h4 class="text-muted margin-bottom">{{ current_user.email }}</h4>

      <div class="list-group">
        <a href="{{ url_for('user.update_credentials') }}"
           class="list-group-item">
          Update email and password
        </a>
        {% if current_user.username %}
          <span class="list-group-item quarter-faded text-muted">
            Your username is
            <strong>{{ current_user.username }}</strong>
          </span>
        {% else %}
          <a href="{{ url_for('user.welcome') }}"
             class="list-group-item">
            Pick a username
          </a>
        {% endif %}
      </div>
    </div>
    <div class="col-md-5 col-md-push-1 col-md-offset-1">
      <h2></h2>
      <p></p>
    </div>
  </div>
{% endblock %}

code/project_services/user/templates/user/signup.html
{% extends 'layouts/app.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Sign up for a new account{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-5">
      <h2>What are you waiting for?</h2>

      <div class="media md-margin-bottom">
        <div class="media-left">
          <i class="fa fa-fw fa-3x fa-bullhorn text-primary"></i>
        </div>
        <div class="media-body">
          <h4 class="media-heading">Place Trades</h4>
          <span class="text-muted">
            Correctly guess the profit.
          </span>
        </div>
      </div>
      <div class="media md-margin-bottom">
        <div class="media-left">
          <i class="fa fa-fw fa-3x fa-database text-primary"></i>
        </div>
        <div class="media-body">
          <h4 class="media-heading">Win Trades</h4>
          <span class="text-muted">
            Gain incoming thru profit taking.
          </span>
        </div>
      </div>
      <div class="media md-margin-bottom">
        <div class="media-left">
          <i class="fa fa-fw fa-3x fa-trophy text-primary"></i>
        </div>
        <div class="media-body">
          <h4 class="media-heading">Leaderboard</h4>
          <span class="text-muted">Compare your results to others.</span>
        </div>
      </div>
    </div>
    <div class="col-md-5 col-md-push-1 col-md-offset-1 well">
      {% call f.form_tag('user.signup') %}
        <legend>Sign up today</legend>

        {% call f.form_group(form.email, css_class='sm-margin-bottom',
                             autofocus='autofocus',
                             placeholder='Email address') %}
        {% endcall %}

        {% call f.form_group(form.password, css_class='sm-margin-bottom') %}
        {% endcall %}

        <div class="row">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              Register
            </button>
          </div>
          <div class="col-md-6">
            <div class="visible-xs visible-sm sm-margin-top"></div>
            <a href="{{ url_for('user.login') }}"
               class="btn btn-default btn-block">
              Looking to sign in?
            </a>
          </div>
        </div>
      {% endcall %}
    </div>
  </div>
{% endblock %}

code/project_services/user/templates/user/update_credentials.html
{% extends 'layouts/app.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Update your sign in information{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-4 col-md-offset-4 well">
      {% call f.form_tag('user.update_credentials') %}
        <legend>Update your sign in information</legend>
        <p class="small help-block sm-margin-bottom">
          Supply your current password to make any changes.
        </p>

        {% call f.form_group(form.current_password, css_class='lg-margin-bottom',
                             autofocus='autofocus') %}
        {% endcall %}

        {% call f.form_group(form.email, css_class='sm-margin-bottom') %}
        {% endcall %}
        {% call f.form_group(form.password, css_class='sm-margin-bottom',
                             placeholder='New password (optional)') %}
        {% endcall %}

        <div class="row">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              Save
            </button>
          </div>
          <div class="col-md-6">
            <div class="visible-xs visible-sm sm-margin-top"></div>
            <a href="{{ url_for('user.settings') }}"
               class="btn btn-default btn-block">
              Nevermind
            </a>
          </div>
        </div>
      {% endcall %}
    </div>
  </div>
{% endblock %}

code/project_services/user/templates/user/welcome.html
{% extends 'layouts/app.html' %}
{% import 'macros/form.html' as f with context %}

{% block title %}Thanks for signing up{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-5">
      <h2 class="sm-margin-bottom">Ready to upgrade?</h2>

      <p class="margin-bottom">
        Hi. You're only about a minute away from being a paid member which
        provides you many amazing things.
      </p>

      <p class="small">
  
      </p>
    </div>
    <div class="col-md-5 col-md-push-1 col-md-offset-1 well">
      {% call f.form_tag('user.welcome') %}
        <legend>Pick a username</legend>
        <p class="small help-block sm-margin-bottom">
          You can only pick this once, make it count.
        </p>

        {% call f.form_group(form.username, css_class='sm-margin-bottom',
                             autofocus='autofocus') %}
        {% endcall %}

        <div class="row">
          <div class="col-md-6">
            <button type="submit" class="btn btn-primary btn-block">
              Save
            </button>
          </div>
          <div class="col-md-6">
            <div class="visible-xs visible-sm sm-margin-top"></div>
            <a href="{{ url_for('user.settings') }}"
               class="btn btn-default btn-block">
              Do it later
            </a>
          </div>
        </div>
      {% endcall %}
    </div>
  </div>
{% endblock %}